name: Generate Swagger Page

on:
  push:
    branches:
        - master
        - dev
  workflow_dispatch:     
  
permissions:
  actions: 'write'
  
jobs:
  generate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn install --frozen-lockfile
    - name: Generate openapi.json
      run: yarn jest -t api-file-generate
    - name: Upload openapi.json
      uses: actions/upload-artifact@v3.1.3
      with:
        name: api-spec-file
        path: swagger.json
  deploy:
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: Download openapi.json
        uses: actions/download-artifact@v2.1.1
        with:
          name: api-spec-file
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1.1.6
        with:
          output: swagger-ui
          spec-file: swagger.json
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-github-pages@v3.1.12
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui
    
